parameters:
    gurme_main.recipe.class: Gurme\MainBundle\Recipe\DataHandler

services:
    gurme_main.recipe:
        class: %gurme_main.recipe.class%
        arguments: [@doctrine.orm.entity_manager]
#        arguments: [@doctrine.orm.entity_manager, "plain_value", %parameter%]
