<?php

namespace Gurme\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends EntityRepository
{
    public function retrieveRecipesWithPhotos($cal = 500)
    {

        return $this->createQueryBuilder('r')
            ->select('r')
            ->where('r.calories >= :start')
            ->andWhere('r.calories <= :end')
            ->setParameters(array('start' => $cal-50, 'end' => $cal+50))
            ->getQuery()
            ->execute();
    }

    public function getIngredients($id)
    {
        $ingredients = $this->getEntityManager()->getRepository('GurmeMainBundle:RecipeIngredient')
            ->createQueryBuilder('il')
            ->leftJoin('il.recipe','r')
            ->leftJoin('il.ingredient','i')
            ->leftJoin('il.unit','u')
            ->select('r.id rid','il.amount','u.main','i.name','il.note')
            ->where('r.id = :recipeId')
            ->setParameter('recipeId',$id)
            ->getQuery()
            ->getResult();

        for ($i = 0; $i < count($ingredients); $i++) {
            if (($ingredients[$i]['amount'] != '')&&($ingredients[$i]['amount'] > 1)) {
                $ingredients[$i]['main'] .= 's';
            }
        }

        return $ingredients;
    }

    public function searchByCalories($calories)
    {

    }
}
