<?php

namespace Gurme\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends EntityRepository
{
    public function retrieveRecipesWithPhotos($cal = 500)
    {

        return $this->createQueryBuilder('r')
            ->select('r')
            ->where('r.calories >= :start')
            ->andWhere('r.calories <= :end')
            ->setParameters(array('start' => $cal-50, 'end' => $cal+50))
            ->getQuery()
            ->execute();
    }
}
